bot:
  name: momTinder_bot
  token: 1869574595:AAFegUz4oJFnjqHcXCXxPCftRHtbhbfCvw8
server:
  port: ${PORT}
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update



