bot:
  name: momTinder_bot
  token: 1869574595:AAFegUz4oJFnjqHcXCXxPCftRHtbhbfCvw8
spring:
  datasource:
    url: jdbc:mysql://us-cdbr-east-04.cleardb.com:3306/heroku_d8199ff?useUnicode=true&characterEncoding=utf-8&reconnect=true
    username: b035a007849916
    password: 8b976819
  jpa:
    hibernate:
      ddl-auto: update




